<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>manzhushaka-scaff</artifactId>
        <groupId>com.manzhushaka</groupId>
        <version>3.9.2</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>manzhushaka-quartz</artifactId>

    <description>
        quartz定时任务
    </description>

    <dependencies>

        <!-- 定时任务 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-quartz</artifactId>
        </dependency>

        <!-- 通用工具-->
        <dependency>
            <groupId>com.manzhushaka</groupId>
            <artifactId>manzhushaka-common</artifactId>
        </dependency>

        <!-- 测试依赖框架权限服务 -->
        <dependency>
            <groupId>com.manzhushaka</groupId>
            <artifactId>manzhushaka-framework</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- 测试框架 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

</project>
