import {
  IconApps,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconCalendar,
  IconCaretRight,
  IconCheck,
  IconCheckCircle,
  IconClockCircle,
  IconClose,
  IconCloseCircle,
  IconCloud,
  IconCode,
  IconCopy,
  IconDashboard,
  IconDelete,
  IconDownload,
  IconEdit,
  IconExclamationCircleFill,
  IconEye,
  IconFile,
  IconFolder,
  IconHome,
  IconImage,
  IconInfoCircleFill,
  IconLeftCircle,
  IconList,
  IconLoading,
  IconLock,
  IconMinus,
  IconMore,
  IconNotification,
  IconPlus,
  IconQuestionCircleFill,
  IconRefresh,
  IconRight,
  IconRightCircle,
  IconSearch,
  IconSettings,
  IconSort,
  IconStorage,
  IconThunderbolt,
  IconUpload,
  IconUser
} from '@arco-design/web-vue/es/icon'

const iconComponents = {
  ArrowDown: IconArrowDown,
  ArrowLeft: IconArrowLeft,
  ArrowRight: IconArrowRight,
  ArrowUp: IconArrowUp,
  Calendar: IconCalendar,
  CaretRight: IconCaretRight,
  Check: IconCheck,
  CircleCheck: IconCheckCircle,
  CircleClose: IconCloseCircle,
  Clock: IconClockCircle,
  Close: IconClose,
  CoffeeCup: IconCloud,
  Collection: IconApps,
  CopyDocument: IconCopy,
  Cpu: IconDashboard,
  DArrowLeft: IconLeftCircle,
  DArrowRight: IconRightCircle,
  Delete: IconDelete,
  Document: IconFile,
  Download: IconDownload,
  Edit: IconEdit,
  Folder: IconFolder,
  InfoFilled: IconInfoCircleFill,
  Key: IconLock,
  List: IconList,
  Loading: IconLoading,
  Lock: IconLock,
  MessageBox: IconNotification,
  Minus: IconMinus,
  Monitor: IconDashboard,
  Odometer: IconDashboard,
  OfficeBuilding: IconHome,
  Operation: IconMore,
  PieChart: IconDashboard,
  Plus: IconPlus,
  PictureFilled: IconImage,
  QuestionFilled: IconQuestionCircleFill,
  Refresh: IconRefresh,
  RefreshLeft: IconRefresh,
  RefreshRight: IconRefresh,
  Right: IconRight,
  Search: IconSearch,
  Setting: IconSettings,
  Sort: IconSort,
  Tickets: IconFile,
  Unlock: IconLock,
  Upload: IconUpload,
  UploadFilled: IconUpload,
  User: IconUser,
  View: IconEye,
  Warning: IconExclamationCircleFill,
  Code: IconCode,
  Storage: IconStorage,
  Thunderbolt: IconThunderbolt
}

export default {
  install(app) {
    Object.entries(iconComponents).forEach(([name, component]) => {
      app.component(name, component)
    })
  }
}
