spring:
  application:
    name: manzhushaka-admin
  profiles:
    active: ${ACTIVE:dev}
  quartz:
    scheduler-name: manzhushaka-quartz
    job-store-type: memory
    properties:
      org:
        quartz:
          scheduler:
            skipUpdateCheck: true
          threadPool:
            threadCount: 5

server:
  port: 8080

sa-token:
  token-name: Authorization
  timeout: 2592000
  is-read-cookie: false
  is-share: false

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

manzhushaka:
  mq:
    group: manzhushaka-group
    consumer: oplog-consumer
    max-retry: 3
